name: 'Sports + Travel Renaissance '
favicon: null
layout_spectrum: 0.38409
typography_spectrum: 0.44966
title: ABUNITED
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff746d'
    - '#ce2431'
    - '#1d100a'
    - '#c8a98a'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
