name: AbUnited
favicon: null
layout_spectrum: 0.24712
typography_spectrum: 0.44966
title: S sense
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff746d'
    - '#ce2431'
    - '#1d100a'
    - '#c8a98a'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
