analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.38409
title: ABUNITED
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.5
  brandStrength: 0
  rhythmicContrast: 0.5
  brandColors:
    - '#ffffff'
    - '#ff746d'
    - '#ce2431'
    - '#1d100a'
    - '#c8a98a'
  lightness: 0.5
purpose: []
favicon: null
name: 'Sports + Travel Renaissance '
typography_spectrum: 0.44966
