name: AbUnited
favicon: null
layout_spectrum: 0.2327
typography_spectrum: 0.44966
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aa2310'
    - '#765858'
    - '#050706'
    - '#ffffff'
    - '#00e0fd'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
